# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ofdm_system/ofdm_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system || ORIG_REF_NAME==ofdm_system} -quiet] -quiet

# IP: bd/ofdm_system/ip/ofdm_system_processing_system7_0_0/ofdm_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system_processing_system7_0_0 || ORIG_REF_NAME==ofdm_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/ofdm_system/ip/ofdm_system_ofdm_axi_lite_0_0/ofdm_system_ofdm_axi_lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system_ofdm_axi_lite_0_0 || ORIG_REF_NAME==ofdm_system_ofdm_axi_lite_0_0} -quiet] -quiet

# IP: bd/ofdm_system/ip/ofdm_system_ps7_0_axi_periph_imp_auto_pc_0/ofdm_system_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==ofdm_system_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/ofdm_system/ip/ofdm_system_ps7_0_axi_periph_0/ofdm_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==ofdm_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ofdm_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==ofdm_system_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.gen/sources_1/bd/ofdm_system/ofdm_system_ooc.xdc
