# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.srcs/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0.xci
# IP: The module: 'ofdm_system_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.gen/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.gen/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.srcs/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0.xci
# IP: The module: 'ofdm_system_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.gen/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/adira/Desktop/OFDM-RTL/ofdm_bd/ofdm_bd.gen/sources_1/bd/ofdm_system/ip/ofdm_system_rst_ps7_0_50M_0/ofdm_system_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ofdm_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
